HaxeFoundation/hashlink

src/alloc.c

The TRAILING_ZEROES macro did not ensure correct evaluation order (it behaved incorrectly when x was a ternary expression for example). To fix this I've replaced these macros with inline functions. Adding brackets around the first x in the TRAILING_ZEROES macro would have worked as well, but we're probably better off using an inline function in this case.
Resolves issue #9

Fix hang on mac and linux

---

Makefile

Don't wanna argue over if 32|64 bit should be the default target, but this sets and uses the LBIT flag to determine the system.
NOT tested on mac/win.

Makefile: set LBITS for 32/64 bit build

---

src/main.c

To output Chinese characters correctly on the Console. 
close #53

Use environment's default locale on Windows

---

libs/sdl/sdl.c
libs/sdl/sdl/Sdl.hx

- detectKeyboardLayout() : returns qwerty, azerty, etc.
- setRelativeMouseMode() : locks the mouse in the active window, see : https://wiki.libsdl.org/SDL_SetRelativeMouseMode
- Quit events are now transmitted to the onEvent callback and can be canceled

Small SDL additions

---

libs/directx/dx/Driver.hx
libs/directx/dx/Loop.hx
libs/directx/dx/Window.hx
libs/directx/window.c
libs/sdl/sdl.c

- SDL: Allowed joystick background events (when the window has lost focus)
- SDL: init_once now throws an exception on failure (with SDL_GetError message)
- DirectX: Added detect_keyboard_layout and win_clip_cursor
- DirectX: Added handling of window close event

SDL & DirectX additions

---

src/module.c

useful when embedding hashlink.
Better look at the diff with `?w=1` since I indented a code block without changing it: https://github.com/HaxeFoundation/hashlink/compare/master...nadako:builtin?w=1

support loading native functions from the main program using special `builtin` name

---

libs/directx/directx.cpp

- Fixed `DXGI_ERROR_INVALID_CALL` on CreateSwapChain by using `D3D11CreateDeviceAndSwapChain`.
- Added `GetDeviceRemovedReason` in `ReportDxError`.

Fixed DirectX createSwapChain

---

libs/directx/directx.vcxproj
libs/directx/directx.vcxproj.filters
libs/directx/dx/GameController.hx
libs/directx/gamecontroller.c

Adds support for both XInput and DirectInput.
DirectInput mappings are based on SDL and is mainly used for Dualshock4.
Requires `dinput8.dll` and `xinput9_1_0.dll` that are both parts of Windows (Vista and next versions).

DirectX GameController

---

.travis.yml
Dockerfile
Dockerfile-i386
Makefile
libs/uv/uv.c

- Added missing dependencies (libuv, openal)
- Added `-pthread` on Linux
- Include `hl.h` before `uv.h` (on Linux uv.h requires _GNU_SOURCE defined in hl.h)

Fixed travis

---

src/std/sys_android.c

with this fix I actually was able to output a hello world with HL/C!

fix android startup crash because of the FindClass typo

---

libs/sdl/sdl.c
libs/sdl/sdl/GL.hx
libs/sdl/sdl/Sdl.hx

Just a few low hanging fruit, nothing particularly interesting.
- new samples option for Sdl.glOptions (does nothing if samples <= 1)
- added GL.DEPTH_CLAMP
- added GL.MULTISAMPLE
- added GL.R11F_G11F_B10F
- added GL.GEOMETRY_SHADER
I've also started on compute, instancing, msaa framebuffers, etc for a later PR.
I've only tested on GL, unsure if these are available on GLES (I think ES 3.2 has all this stuff?)

SDL/GL: Add backbuffer msaa and some missing enum values

---

libs/sdl/gl.c
libs/sdl/sdl/GL.hx
libs/sdl/sdl/Sdl.hx

Typo in the function signature for drawArraysInstanced makes it do very bad things, as discovered by freezing my dev machine. I strongly recommend that nobody tries to use GL.drawArraysInstanced without this fix.
Otherwise, just a bunch of boring enum values here.

Fixed GL.drawArraysInstanced, more texture flags.

---

src/track.c

Is somehow the first hash calc resulting in 0, matching the init conditions of prev_hash / prev_hash2 ?

Missing (apparently required) null checks, on_alloc was insta-crashing on Linux

---

Makefile

Linux users expect the PREFIX variable respected for the install path.
For a custom install path you still can set INSTALL_PATH which defaults to PREFIX (if set), otherwise /usr/local like before.

Use PREFIX variable for INSTALL_PATH if set

---

src/hl.h
src/hlc_main.c

MinGW headers just lowercase everywhere. So cross compilation detection not needed.
clang -target i686-pc-windows-gnu macros must be apended to defines, if this commit won,t breake anything.
P. S. English is not my native language sorry for possible mistakes.

fix #187 Mingw headers are lowercase

---

Makefile
include/minimp3/LICENSE
include/minimp3/README.md
include/minimp3/minimp3.h
libs/fmt/CMakeLists.txt
libs/fmt/fmt.c
libs/fmt/fmt.vcxproj
libs/fmt/fmt.vcxproj.filters

Introduces MP3 decoder support. Utilizes [lieft/minimp3](https://github.com/lieff/minimp3) library to decode mp3.
Exposes two functions:
- `mp3_open(bytes, size)` - allocates reader structure.
- `mp3_decode_frame(mp3, pos, output, size, offset)` - reads frame at `pos` and outputs to `output + offset`.
Notes/concerns/details:
* I use `Float32` output mode instead of `Short`.
* I don't like double-buffering instead of direct write to `output` on `mp3_decode_frame`.
* There is no checks if frame will fit into output and it may corrupt memory due to that.
* Probably worth adding ability to read multiple frames at once, since 44100 mp3 will read a bunch of frames at once to fill the audio buffer.
I'm not very confident with C code, and would appreciate comments on how to improve this …

Add MP3 decoder to fmt

---

libs/directx/dx/Window.hx
libs/directx/window.c
libs/sdl/sdl.c
libs/sdl/sdl/Window.hx

I wanted to provide some additional options to my own HashLink window in Heaps, so I went ahead and added a couple extra things to both window implementations. Figured they may be worth a pull request here.
_**Original Synopsis**_
The option to enable user resizing of the window can be enabled or disabled upon initialization (through constructor parameters) for both DirectX and SDL windows. A new method was created for the C bindings in order to maintain compatibility.
SDL was provided with position getters and a position setter method to match DirectX's implementation. Furthermore, both window implementations were provided with a method to center the window to the screen.

Add resizability configuration and screen centering for DirectX and SDL windows

---

libs/directx/dx/Cursor.hx
libs/directx/window.c
libs/sdl/sdl.c
libs/sdl/sdl/Cursor.hx

At the current moment, the DirectX's cursor implementation is completely broken. The cursor only changes for a bit, but reverts back immediately since the WM_SETCURSOR event is not handled. Another issue is that "hiding" the cursor doesn't just hide it in the client area, but the entire application including the title bar (making it difficult to move, close, etc.).
This pull request fixes both issues and also adds a method for checking cursor visibility on both DX and SDL.

Fixed DirectX Cursor

---

libs/directx/dx/Window.hx
libs/directx/window.c
libs/sdl/sdl.c
libs/sdl/sdl/Window.hx

I've exposed SDL's functions for optionally providing a minimum and maximum size for windows along with the ability to set a window's opacity. These features have also been ported over to the DirectX implementation; as usual, they are based off of SDL's in order to provide consistency.

Add Minimum/Maximum Size and Opacity Configuration for Windows

---

Makefile
src/alloc.c
src/main.c
src/std/thread.c

Fix for deprecated `syscall(SYS_getid)` comes from here:
https://github.com/PowerShell/PowerShell/pull/2675/files
Is there some test I can do to verify this is working correctly? Also suspect return type (uint64) is an issue – bear in mind I know nothing about C programming, just trying to help ;)

Fix macos warnings

---

Makefile

This change allows the use of `hl` locally on Linux without it being installed to the system
```
make libhl
make hl
./hl
```

Allow use of libhl.so in the same directory

---

Makefile

This change allows for the developer to specify a macOS SDK version. This is important in order to build HashLink for older macOS systems, while building on a newer system.
I debated whether this should have a different variable name (such as `SDK_VERSION`), but thought SDK would be easier to remember, and more convenient if you do not have to try and find the full SDK path yourself
```
make SDK=10.14
```

Let macOS build set the SDK version

---

src/module.c

As we discussed yesterday on Slack.

use the actual module handle instead of the calling process handle (windows)

---

src/std/string.c
src/std/sys.c
src/std/ucs2.c

- ~~convert to UTF-16 before printing in `sys_print` (similar to the fix in hxcpp)~~
- ~~`0xD7C0` was used instead of `0xD800` for high surrogates~~

Unicode fixes

---

libs/directx/dx/Event.hx
libs/directx/window.c
libs/sdl/sdl.c
libs/sdl/sdl/Event.hx

Introduces `Event.scanCode` to both SDL and DirectX on `KeyDown` and `KeyUp` events. 
Reasoning behind that is that `keyCode` acts more like `charCode` and depends on what active keyboard layout user have, making it less consistent.
And since we're not living in PS/2 era and all normal people use USB keyboard, scan codes should be persistent and reliable way that is not reliant on active layout. 
Related: HeapsIO/heaps#492

Add scanCode to SDL and DX keydown/keyup events.

---

src/std/date.c

See HaxeFoundation/haxe#8508
- add `date_get_utc_inf` - same as `date_get_inf`, but using `gmtime_r` instead of `localtime_r`

Add UTC-based methods

---

src/std/sys.c

#281 
_Originally posted by @Shoozza in https://github.com/HaxeFoundation/hashlink/pull/281#issuecomment-523223056_
[GetSystemTimePreciseAsFileTime](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) supported since Windows 8
[GetSystemTimeAsFileTime](https://docs.microsoft.com/ru-ru/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimeasfiletime) supported since Windows 2000 Professional

update hl_sys_time to support OS below Windows 8

---

src/std/regexp.c

Option to disable utf8 checks every regexp_match call
check off: `0.11178874969482s`
check on: `2.42371964454651s`
Sample code:
```haxe
class Main 
{
static function main( )
{
var str = StringTools.lpad('', '"', 10 * 1024);
var r = ~/"/g;
haxe.Timer.measure(function(){
for(i in 0...10)
replace(r, str);
});
}
static function replace( r : EReg, str : String )
{
str = r.replace(str, '');
}
}
```

add PCRE_NO_UTF8_CHECK option

---

Makefile

The library paths included in the Mac section of the Makefile
don't correlate to the locations used by Homebrew
As Homebrew is the [recommended installation approach for Mac](https://github.com/HaxeFoundation/hashlink/blame/master/README.md#L26)
this should improve the setup experience for newcomers
Issue: #256

Fix library path in Mac Makefile (close #256)

---

libs/fmt/CMakeLists.txt

Compile fmt.hdll with libs/fmt/mikkt.c and include/mikktspace/mikktspace.c for all OSes.

libs/fmt: Compile fmt.hdll with mikktspace

---

libs/sdl/sdl.c

It works the same as setting the displayMode to 1, Fullscreen. It seems better than not doing anything on non-windows platform when trying to set the mode to Borderless.

Added possibility to switch to borderless fullscreen on non windows

---

libs/sqlite/sqlite.c

For properly allocating BytesData need actual length of bytes.

add bytes length to sqlite bytes of BLOB

---

Makefile
other/azure-pipelines/build-mac.yml

This tiny PR fixes two issues related to codesigning in OSX:
1) The "hl-cert" signing identity is now removed prior to generating a new certificate, rather then after. This prevents duplicate certificates of the same name – which is actually possible – being created when the command fails before the signing identity could be removed in the old version.
2) There is an issue with MacOS's security during `make install` which does not allow replacement of differently signed `hl` executables in `/usr/local...`. We therefore need to explicitly uninstall and then install to make this possible and prevent signing corruption
@qkdreyer @ncannasse

minor improvements to OS X installation routine

---

src/main.c

Currently, when running on linux (didn't test on macos) if remote socket hangs up the whole application silently crashes with SIGPIPE (and no stacktrace). I traced it all the way to libuv that does this on purpose for performance reasons (see https://github.com/joyent/libuv/issues/1254#issuecomment-41185781). The recommended (as I understood it) way to prevent crashes is to redirect SIGPIPE to SIG_IGN and handle socket errors in user code instead.

[UNIX] Don't crash on SIGPIPE

---

Makefile

This is required by Homebrew https://github.com/Homebrew/homebrew-core/pull/53790#issuecomment-637662089 because it installs hashlink's `hddl`-s outside of `/usr/local/lib`.

Allow passing extra linker flags

---

src/std/debug.c

The current usage of USE_PTRACE depends on some x86-isms, which just break the build on ARM. This fixes hl/c build on Raspberry Pi.

Fix build for ARM Linux

---

Makefile
src/std/maps.c
src/std/maps.h
src/std/regexp.c

So for starters, I fixed the installation issue on Linux that everyone seems to be complaining about.
Secondly, I added 2 (technically 4) functions to the builtin stdlib, which is step 1 of several for a PR that I'm working on for Haxe.
The functions are as follows:
- `hisize`/`hbsize`/`hosize`: Return the number of entries in the map.
- `regexp_matched_num`: Return the number of matched groups from the last time a regexp was matched.

Fix linux Makefile flags and new function for maps/regexps

---

other/haxelib/templates/vs2019/__file__.sln
other/haxelib/templates/vs2019/__file__.vcxproj
other/haxelib/templates/vs2019/__file__.vcxproj.filters

Add the Visual Studio 2019 project templates so that the library can also generate those with the `-D hlgen.makefile=vs2019` flag.

Add vs2019 template files

---

src/gc.c
src/main.c
src/module.c

Closes #452 (at least i cannot reproduce the failure with 3 reloads anymore).
Two things so far that i found that make cleanup in main not complete:
- In `main` there is a call to [`hl_register_thread`](https://github.com/HaxeFoundation/hashlink/blob/c2786410a0fc525edda88b266fee1158efc38f44/src/main.c#L207), but no call to `hl_unregister_thread` at the end. (For `main` itself it is ok since it does not care much about full cleanup before exit, but it can be used as a reference point for proper integration and better to make it right.)
- In `hl_module_init` globals are passed to [`hl_add_root`](https://github.com/HaxeFoundation/hashlink/blob/c2786410a0fc525edda88b266fee1158efc38f44/src/module.c#L521), but in `hl_module_free` globals [are …

fix cleanup for main

---

src/gc.c

In case prev_stack is not pointer-aligned, the extra_stack_data contains a misaligned copy of the stack piece, which prevent garbage collector to discover saved register.

Fix gc_save_context when prev_stack is not pointer aligned

---

src/profile.c

Implement profiler for linux.

---

.github/workflows/build.yml

@ncannasse GHA build fails because I had to disable 32bit Linux builds but the release step still tried to upload the (not-build) 32bit binaries

GHA: Don't try to upload non-existing 32bit binaries

---

src/hl.h
src/std/thread.c

Semaphores and condition variables.

---

src/hl.h

This is needed when (for example) building hashlink with the hxcpp build tools, since hxcpp adds `-fvisiblity=hidden`.

Make HL_API/HL_PRIM function have default visibility.

---

.github/workflows/build.yml

This PR downgrades the GHA build from Ubuntu 20 to 18 to address #525. It also changes the windows runner from windows-2016 to windows-2019 as the former has been decomissioned.

Build with Ubuntu 18 and Windows 2019

---

other/azure-pipelines/build-linux.yml
other/azure-pipelines/build-mac.yml

Azure pipelines removed ubuntu 16.04
Building on macos 10.14 wasn't getting past installing dependencies with homebrew.
Closes #514.

[ci] Update linux and mac environments

---

src/hl.h
src/profile.c
src/std/bytes.c
src/std/ucs2.c

Allow all whitespaces and + in front of hexadecimal number. Also, allows trailing text after hexadecimal number, like after normal number.
Related to #477.

Fix parse_int with hexadecimal notation

---

.gitattributes

Marks all directories in `include` as third party libraries. This way they do not count to the overall line count of hashlink.

Mark `include` directories as third party for github

---

.github/workflows/build.yml
Brewfile
Makefile
README.md
other/azure-pipelines/build-linux.yml

Related to #323.
Closes #347 and closes #460.

[make] Add sqlite.hdll target

---

src/hl.h

Compiler is not happy about casting `void*` into `vdynamic*` implicitly. Fixes usage of said macros.

Fix hl_call macros

---

Makefile

This way OpenGL is correctly linked. Fixes #549.

Add -lGL to sdl.hdll build

---

libs/sdl/CMakeLists.txt

On openSUSE the packages are build with -Wl,--no-undefined and it would fail because of missing symbols

cmake: Link sdl.hdll with OpenGL

---

Makefile

The wrong variable was being used when building the regex part of the
standard library which was preventing compilation without a global
installation.
Only required if #515 is not merged first.

Fix make error related to pcre

---

src/hl.h

This isn't an issue when compiling HashLink alone, but causes warnings when compiling it alongside other libraries [such as SDL](https://github.com/libsdl-org/SDL/blob/f0566702c5e4c3522148fca6c65e83fb57326ddb/src/SDL_internal.h#L24-L27).
The warnings don't interfere with compilation, but given that the solution is so simple, why not fix them?

Avoid redefining `_GNU_SOURCE`.

---

src/hl.h
src/std/thread.c

The JIT implementation is based on what GCC emits for it's intrinsics.
The C implementation is copy pasted from what I did for hxcpp.
See https://github.com/HaxeFoundation/haxe/pull/10610

Atomic operations.

---

src/gc.c
src/hl.h
src/profile.c
src/std/file.c

Added the necessary conditional logic to support the Hashlink profiler on Mac (Intel Only).

Feature - Mac profiler support

---

src/std/regexp.c

e.g.
LINK : warning LNK4217: symbol 'pcre2_compile_16' defined in 'pcre2_compile.obj' is imported by 'regexp.obj' in function 'hl_regexp_new_options' [D:\a\hashlink\hashlink\libhl.vcxproj]

Fix linker warnings from pcre

---

src/std/thread.c

In some systems (target language C), we'll fall under the [else condition of hl_thread_id](https://github.com/HaxeFoundation/hashlink/blob/master/src/std/thread.c#L815), which will throw an exception till now. It will prevent the use of multithread in these systems (called by hlc_main->hl_register_thread->hl_thread_id) even if they support posix. This is not an fatal error if we do not need `hl_thread_set_name` and `hl_thread_get_name`.
This commit remove the hl_error.

Prevent hl_thread_id throw error even when we can't get a tid

---

other/memory/Memory.hx

Pressing enter on empty prompts in the memory tool will not display "Unknown command" anymore

Allow skipping lines without error on memory tool

---

libs/directx/dx/Cursor.hx
libs/directx/dx/Driver.hx
libs/directx/dx/Format.hx
libs/directx/dx/Resource.hx
libs/directx/dx/Window.hx
libs/sdl/sdl/Cursor.hx
libs/sdl/sdl/Event.hx
libs/sdl/sdl/Sdl.hx
libs/sdl/sdl/Window.hx
other/memory/Block.hx

Although the changes are straight forward, I didn't manage to test them properly, because I didn't figure out how to add the repo as the git version to use for hlsdl in particular.

Remove deprecated use of @:enum abstract

---

src/hl.h

Defining uchar as `uint16_t` causes errors when using unicode literals in C++,
because in C++ `char16_t` is not the same type as `uint16_t`.

Fix uchar on macOS.

---

src/std/socket.c

Hello,
Trying out heaps.io, I noticed, that the implementation for sockets was missing the `setBroadcast` function for udp.
I hope I implemented this correctly as it isn't a big diff. 
I tested sending broadcasts with ubuntu 20.04, haxe 4.1.4, heaps 1.8.0
They showed up in wireshark and I could recieve them on another machine in the same network.

add broadcast ability to udp sockets

---

libs/directx/dx/Event.hx

Looks like these got missed in be64c2c86ad47b75ba0d1e5d72bbac443e9f3b75

Fix deprecated @:enum metadata in Event.hx

---

other/memory/Memory.hx
other/memory/TType.hx

This PR improves the other/memory dump inspector:
- You can now specify multiple .dump on startup.
- By default only the first is used
- After doing `filter unique` only blocks that are only in the first .dump will be shown
- After doing `filter intersect` only blocks that are in every .dump will be shown
- Using `-c` or `--color` from the command line will print with ansii-escaped colors (works on linux and windows terminal, but not on the cmd.exe window)
- Functions are now displayed as `Function(Void -> Void)` making it easier to distinguish from parenting `>`

Improve memory dump tool readability

---

libs/directx/dx/Event.hx
libs/directx/dx/Window.hx
libs/directx/haxelib.json
libs/directx/window.c
libs/sdl/haxelib.json

Adds D&D support for DirectX in a similar fashion to hlsdl. There are some caveats thought.
Small note on buffer formatting: SDL implementation requires `String.fromUTF8` (since SDL buffer is UTF8) to convert the buffer into Haxe String. DX needs `String.fromUCS2` as it's raw `DragQueryFileW` buffer output.
Big note on GC shenanigans:
Due to the fact that events are queued and consumed asynchronously - string buffers of dropped files are added to gc root, as well as require extra checks on event type when consuming events/destroying window. This is mandatory, because when buffer is not rooted - if GC runs in any circumstance - we get garbage data on event consume stage. And extra checks on type are here to ensure there's no gc root memory leaks.
This _could_ be alleviated if `dx_event*` …

[hldx] Implement Drag&Drop api

---

src/hlc_main.c

Following #632 , I tried some implementation for hlc stack trace on Linux/MacOS using `<execinfo.h>`.
I did not use libunwind, as it does not seems to be adapted to the current structure: `uwn_backtrace` does not have more collaboration with other functions; resolve symbol of a single address would require to iterate though the stack.
I made a simple test with main() calling SimpleTest.hx, try catch and display the stack.
On Linux (gcc parameter `-rdynamic` is necessary to resolve function name):
```
Called from module ./bin/c/hlout/a.out(haxe_Exception_thrown+0x13d) [0x55f5d42fa5ed]
Called from module ./bin/c/hlout/a.out(SimpleTest_runThrowTest+0x617) [0x55f5d43024e7]
Called from module ./bin/c/hlout/a.out(fun$init+0x2156) [0x55f5d4306236]
```
On Mac:
```
Called from module 0   a.out …
```

Add hlc stack trace to Linux/Mac

---

.github/workflows/build.yml
Brewfile

- mbedtls@2 is keg-only, so it needs to be explicitly force-linked
- Switch to macOS 12, Homebrew doesn't support 11 anymore
- Remove all pre-installed homebrew packages to prevent any issues during brew bundle.
(This is probably overkill, but I do not have a better fix for now. Will send a follow-up PR if I find a better solution.)

Make macOS CI green again.

---

.github/workflows/build.yml

openal-soft.org is down, but a Github release is available for the latest version.

Update OpenAL download link.

---

libs/sdl/gl.c
libs/sdl/sdl/GL.hx

Apple platforms only support up to OpenGL 4.1.

Disable certain OpenGL functions on Apple platforms.

---

src/std/process.c

The Hashlink profiler causes some Linux system calls to be interrupted. Previously, error handling was added for `std/file.c` read/write operations. However, the read/write calls made by sys.io.Process use instead the unistd read/write functions which are also [affected by the interrupts](https://github.com/HaxeFoundation/hashlink/issues/650).
This pull request extends the [previously introduced error handling](https://github.com/HaxeFoundation/hashlink/commit/775d53e7c53508bac784cd05e9bd96278b4f5ef7) also to the unistd read/write calls in `std/process.c`.
The behaviour can be tested with the following program, which uses the stdout, stderr and stdin streams via sys.io.Process:
```haxe
import sys.io.Process;
class Main
{
static public function main():Void
{
var cat = new Process('cat'); …
```

Retry interrupted std stream read/write calls.

---

src/gc.c

For https://github.com/HaxeFoundation/hashlink/issues/656 , usage (API should be in haxe someday with hl_ver >= 1.15.0):
```haxe
class MemoryTools {
/**
Count live objects of a given class and get at most `maxCount` elements in an array.
**/	
public static function getLiveObjects(cl : Class<Dynamic>, maxCount : Int = 0) {
var arr = new hl.NativeArray<Dynamic>(maxCount);
var count = _getLiveObjects(cast(cl,hl.BaseType).__type__, arr);
var objs = new Array<Dynamic>();
for (i in 0...maxCount) {
if (arr[i] == null) break;
objs.push(arr[i]);
}
return { count : count, objs : objs };
}
@:hlNative("std", "gc_get_live_objects")
static function _getLiveObjects(type : hl.Type, arr : hl.NativeArray<Dynamic>) : Int { return 0; }
}
```
Then,
```haxe
MemoryTools.getLiveObjects(h2d.col.Point.PointImpl, …
```

Add get live objects

---

src/std/thread.c

Add hl_blocking calls in blocking semaphore and condition functions.

---

src/jit.c

Fixes https://github.com/HaxeFoundation/hashlink/issues/142 , fixes https://github.com/HaxeFoundation/hashlink/issues/658 for me without breaking our game on Linux (Ubuntu 22.04).
I'm not very sure what I'm doing, so here is some description:
I found that Linux & Windows have different set of CPU registers (if I use the same cpu set, I have segfault)
https://github.com/HaxeFoundation/hashlink/blob/8bc5f8f0d21c38805ca3457e5298a27d96c396ad/src/jit.c#L227-L239
Esi, Edi are used in Linux, however they are not 8 bit register (remove the id check on RCPU fixes the issues, but will make our game to exit "normally" without actually run and I don't understand why)
https://github.com/HaxeFoundation/hashlink/blob/8bc5f8f0d21c38805ca3457e5298a27d96c396ad/src/jit.c#L542-L544
The UI8 op failed during a …

Fix UI8 assign on Linux

---

libs/sdl/sdl.c
libs/sdl/sdl/Sdl.hx

This allows us to track drag/resize movements that go outside the window; fixing the issue where dragging too fast will lose a handle on the window. The motivation behind this feature is to support ImGui multi-window viewports
Viewports will function without this, but moving/resizing windows sucks, as the mouse can move more than the title bar's width per frame, causing it to lose track of the window and "drop" it.
Unsure if there's a parallel to this in DX, but we can't use that backend currently anyway since it lacks single driver multi window support at the moment. Given this limitation I'm unsure there's any value in adding a similar function or common routing in hldx, but I can do this work if it's necessary for merge.

Add support for SDL_GetGlobalMouseState

---

libs/sdl/sdl.c

This is an operator precedence bug introduced in https://github.com/HaxeFoundation/hashlink/commit/1d54fc5734757d7e050bae0d0ce80d28d9d01121, and due to changes in defaults prevents SDL from working on PC.
As written, with C++ operator precedence, this check does not do what you'd expect and `SDL_WINDOW_OPENGL` never gets set. This change simply adds missing parenthesis to force the bitwise ops to resolve before equality checks.

Fix SDL failing to initialize on desktop (C4554)

---

libs/mysql/my_api.c
libs/mysql/socket.c
libs/sqlite/sqlite.c

This fixes errors encountered when compiling Hashlink on Arch Linux and Fedora.

[mysql] Fix compilation.

---

src/gc.c

With the current code the `pextra *` pointer could be in `[page_ptr, page_ptr+size]` interval, which is incorrect.
There probably was a missing `+ size`  in `(char*)ptr + EXTRA_SIZE - sizeof(pextra)`.
But as we have an extra size at the end :
`#define EXTRA_SIZE (GC_PAGE_SIZE + (4<<10))`) 
Let's store that extra header always at the end.

Fix extra page header memory address

---

src/hl.h
src/std/error.c

This enables `hl.Api.breakPoint()` and catching exceptions.

Fix hl_debug_break and hl_detect_debugger on Linux.

---

.github/workflows/build.yml
libs/ssl/ssl.c

- get rid of the brew uninstall hack, it doesn't seem to be needed anymore
- only define MSG_NOSIGNAL if it is actually undefined
- Use `SecTrustCopyAnchorCertificates` to get root certs on macOS instead of the deprecated keychain apis.
- Initialize PSA crypto when it is present (in mbedtls 3.6 TLS 1.3 support is turned on by default which uses PSA crypto)
The partially fixes the macOS HTTPS failures encountered in https://github.com/HaxeFoundation/haxe/pull/11638.

SSL bugfixes.

---

src/jit.c

Fixes #688 : `OCallMethod obj f args` where obj is also in args list. Inspired by OCallClosure.
Haxe compiler does not generated this bytecode in most cases, so I choose to keep the o->value hack if the new logic is not necessary.
I also tested when using only the new logic (keep o->value in R(f->nregs)) and it seems to work fine.

Fix OCallMethod on HVirtual, when obj is in args

---

src/hlc_main.c

Closes #687
These issues were errors with GCC, but they were also warnings on MSVC.

Fix mingw errors in hlc_main.c

---

libs/sdl/gl.c

I'm not familiar with `glMultiDrawElementsIndirectCountARB` so please confirm this fix is valid.
I had to do this cast for `gcc 14.1.1`.

Fix gl.c for gcc 14.1.1

---

.github/workflows/build.yml
CMakeLists.txt
Makefile

This ensures that the build works and passes the hlc tests on arm64 mac. It also releases binaries for the libraries, but not the `hl` binary since that is not supported on arm64.
Closes #521.

[ci] Run hlc tests on arm64 mac

---

libs/CMakeLists.txt
libs/directx/CMakeLists.txt

~~Also remove FindDirectX.cmake, as directx should now be found in the Windows SDK.~~

[cmake] Add dx12.hdll to build

---

src/std/thread.c

"hl_thread_set_name" also isn't available on iOS. I would assume tvOS too, but could not test myself

Fix compile issue for iOS

---

other/haxelib/templates/vs2015/__file__.vcxproj
other/haxelib/templates/vs2017/__file__.vcxproj
other/haxelib/templates/vs2019/__file__.vcxproj

Currently, each file requires a separate cl.exe invocation. This PR reduces the number of cl.exe invocations needed to build the project by allowing multiple files to be compiled in the same cl.exe invocation (by passing [object output directory instead of object output file name](https://learn.microsoft.com/en-us/cpp/build/reference/fo-object-file-name?view=msvc-140), which means more files share the same compilation arguments). This already gives a noticeable speed up.
It further improves the speed by enabling [multi processor compilation](https://learn.microsoft.com/en-us/cpp/build/reference/mp-build-with-multiple-processes?view=msvc-170), which is possible now that the same cl.exe invocation deals with multiple files.
As an example, on my machine with the HelloWorld program in …

[hlc] Speed up hlc visual studio templates

---

other/haxelib/templates/vs2015/__file__.vcxproj
other/haxelib/templates/vs2015/__file__.vcxproj.filters
other/haxelib/templates/vs2015/stdafx.c
other/haxelib/templates/vs2015/stdafx.h
other/haxelib/templates/vs2017/__file__.vcxproj
other/haxelib/templates/vs2017/__file__.vcxproj.filters
other/haxelib/templates/vs2017/stdafx.c
other/haxelib/templates/vs2017/stdafx.h
other/haxelib/templates/vs2019/__file__.vcxproj
other/haxelib/templates/vs2019/__file__.vcxproj.filters
other/haxelib/templates/vs2019/stdafx.c
other/haxelib/templates/vs2019/stdafx.h

Instead of having to recompile the headers for each individual source file, the headers are now compiled once for the whole project. This gives a further speed up from ~7 seconds to ~3 seconds.

[hlc] Use precompiled headers in vs templates

---

.github/workflows/build.yml

The macOS 12 runner image is deprecated and will be removed soon: https://github.com/actions/runner-images/issues/10721

Bump x86_64 macOS runner to macOS 13.

---

other/haxelib/hlmem/Memory.hx

This allows doing locates on types containing spaces
With -c, this displays like this 
And then doing `locate #45319` yields things referencing the `Function(Void -> Void)` type

hlmem: Add type id to print and allow doing locate on type ids

---

other/haxelib/hlmem/Memory.hx

Blocks with the same address but varying types and size will not be considered the same block anymore

Fix filtering another memory dump from memory tool

---

src/module.c

In the following code based on https://github.com/HaxeFoundation/hashlink/issues/145 , uncomment `trace` after launch will
- successfully print once after the first reload (4 changes detected: modified `foo`, `entrypoint`, new `haxe.Log.formatOutput`, `haxe.Log.trace`),
- note that if we do not run any `hl.Api.checkReload` after the first reload, the program runs correctly.
- then read access violation after the second reload (2 changes detected, even no change on hl bytecode: new `haxe.Log.formatOutput`, `haxe.Log.trace`) at the beginning of `foo()`, probably `global 2, 9 field 1,2[6]` with `global 9: haxe.$Log`.
```haxe
class Main {
static var g1 = 0;
static function foo() {
// haxe.Log.trace("additional print"); // <- after launch, uncomment this line and save
return 10000 + g1++;
} …
```

Hot Reload: fix new global not initialized

---

Makefile

We do not need to add all the individual include/library paths, most of them are linked to the main homebrew prefix so we can just add that instead.
Only openal-soft is keg-only so it doesn't get linked to the main prefix.
Previous version also ended up with a lot of duplicate include paths being added.

[make] Clean up homebrew package config

---

.github/workflows/build.yml

The Ubuntu 20.04 runner will begin deprecation in February and be fully unsupported by April: https://github.com/actions/runner-images/issues/11101

[ci] upgrade to Ubuntu 22.04

---

other/haxelib/Run.hx
other/haxelib/templates/vs2015/__file__.vcxproj
other/haxelib/templates/vs2017/__file__.vcxproj
other/haxelib/templates/vs2019/__file__.vcxproj

Add jumbo build (aka unity build but I prefer avoid using "unity") for hlc templates and use it by default for better hlc compilation speed with Visual Studio (especially when use hl/jit for dev and hl/c for release).
If incremental build is preferred, jumbo build can be disabled by setting `-D hlgen.nojumbo`.
@tobil4sk made a couple of tests and it turns out that this all-in-one build strategy is still the quickest and is a known approach. It's already used internally in Shiro's project but was made by manually editing vcsproj file.

[hlc] Add jumbo build for vs template

---

src/std/process.c

When running `process_stdin_close`, the handle is made available again and may be reused in another part of the program. This means that it is not safe to rerun `CloseHandle` in `process_finalize`, since that could cause us to close a handle that no longer belongs to the process.
See: https://github.com/HaxeFoundation/neko/pull/300

[std] Prevent process stdin being closed twice

---

src/std/cast.c

Should fix @jacobalbano 's error on JIT, see https://github.com/HaxeFoundation/hashlink/issues/735#issuecomment-2677052049
Callstack:
```
libhl.dll!hl_make_dyn(void * data, hl_type * t) Line 78
libhl.dll!hl_dyn_castp(void * data, hl_type * t, hl_type * to) Line 222
libhl.dll!hl_wrapper_call(void * _c, void * * args, vdynamic * ret) Line 327
libhl.dll!hl_dyn_call_obj(vdynamic * o, hl_type * ft, int hfield, void * * args, vdynamic * ret) Line 352
```

Fix cast from void to dynamic cause segfault

---

src/jit.c

Previously, assign a `@:struct` var to a `@:packed` field is not supported, and will result in wrong value (copying struct's pointer instead of its value).
This PR fix it by generate copy instructions (MOV) of appropriate size when we have `@:packed <- @:struct` in `OSetField` / `OSetThis`.
A test will be added in haxe with corresponding fix to hl/c.

[jit] Fix assign struct to packed, generate copy op

---

CMakeLists.txt

This is the version shipped by Debian Buster (oldoldstable)

[cmake] Bump minimum required version to 3.13.

---

src/jit.c

We have an access violation when manipulating CArray:
```haxe
var nodes : hl.CArray<TreeNode>;
public function addBody(aabb : AABB, id : BodyID ) : Int {
var nodeID = addObjectInternal(aabb); // OCall2
var node = nodes[nodeID]; // OGetThis, OGetArray
node.bodyID = id; // OSetField, *access violation*
return nodeID;
}
```
It generates the following assembly without taking into account that only `eax` part is valid for `rb` at this time
```assembly
000076CA9F330126  imul        rax,rax,2Ch
000076CA9F33012A  lea         r8,[rdx+rax]           ; RAX might be invalid (higher part is not 0), EAX = nodeID
000076CA9F33012E  mov         qword ptr [rbp-18h],r8
000076CA9F330132  mov         r9d,dword ptr [rbp+20h]
000076CA9F330136  mov         dword ptr [r8+0Ch],r9d ; *Access violation* with invalid …
```

[jit] Fix OGetArray pmem2 on cpu32 access violation

---

src/jit.c

Fix hl.CArray.unsafeSet in hl/jit. Use a copy struct approach similar to
- https://github.com/HaxeFoundation/hashlink/pull/758 (if the obj is big, we'll probably need some memcpy)
I don't think CArray can contains other things than obj/struct with the haxe fix (was Dyn for struct), but the isRead/isWrite check here help avoid assert/segfault with hl bytecode generated before the haxe side fix.

[jit] Fix CArray OSetArray (hl.CArray.unsafeSet) not working

---

src/std/buffer.c

In Buffer.c, when a pointer is null, it can be print as either "NULL" (in `hl_buffer_str`, `hl_buffer_cstr`) or "null" (in `hl_buffer_rec`, `hl_to_string`).
This is not consistent in the following case
- ref https://github.com/HaxeFoundation/haxe/pull/12143
```haxe
class M {
var __exceptionMessage:String;
public function new(value:Any) {
__exceptionMessage = value;
}
public function toString():String {
return null;
}
}
class Main {
static function main() {
var m = new M(null);
trace(m.toString()); // null
trace(Std.string(m)); // NULL <- hl_value_to_string(m) -> hl_buffer_rec -> HOBJ toStringFun hl_buffer_str
}
}
```
This PR unify them and use "null".

Buffer: unify null print to null

---

src/hlc_main.c

`new haxe.Exception('')` generate a call to `__nativeStack = NativeStackTrace.callStack();`
Which first call `capture_stack` function with `null` to get the total count
https://github.com/HaxeFoundation/hashlink/blob/f1ef2cf01cd6eee0dc35e6b198cd74acd78d2887/src/std/error.c#L167-L171
However it does not work as expected on hl/c (win/mac/linux), which only return at most `size` as count. And `__nativeStack` will receive an 0-length array as result. This PR fixes it.

[hlc] fix hlc_capture_stack not returning total count with empty stack

---

src/std/sys.c

See
- https://github.com/HaxeFoundation/haxe/pull/12148#issuecomment-2796653301
TLDR: copy the order in hxcpp, so maybe the haxe CI will be happy

Sys: sys_exe_path Linux use readlink before env _

---

src/std/buffer.c

Repro:
```haxe
@:struct class Point {
public var x : Int;
public function new( x : Int ) { this.x = x; }
public function toString() : String { return 'Point(x=$x)'; }
}
class Main {
static function main() {
var nativeArr = new hl.NativeArray<Point>(10);
for( i in 0...10 ) {
nativeArr[i] = new Point(20+i);
}
trace(nativeArr); // Access violation
}
}
```

Buffer: fix Std.string NativeArray<struct> access violation

---

.gitignore
src/gc.c

because the insertion order of `gc_roots` list doesn't matter it's possible remove the `memmove` usage and just move the last root from the list to the found root position.

[gc] remove `memmove` usage in hl_remove_roots

---

libs/directx/window.c

Sometimes, with DX on startup, we can end up in a case where the window have focus but is not foreground (some other window may hide partially or totally the game window).
This PR prevent ClipCursor when the window is not foreground.
An example of repro is:
- click another window during startup
- lock session (Win+L), * it's not necessary but will make the repro 100% in my case
- wait for game to launch
- unlock session *
Note: if `relative_mouse` is set, `WM_INPUT` event is not received by not-foreground window.
Note2: it's possible fake a Focus/Blur event for haxe side, but might have unwanted effect.

[dx] Prevent ClipCursor when window have focus but is not foreground

---

src/hl.h
src/hlc_main.c
src/main.c
src/std/error.c

This allows printing custom exception stacks on uncaught exceptions in case we have an instance of `haxe.Exception` which has `_hx_customStack` set. This will be useful for the coroutine implementation.
It's currently broken because `uprintf` should apparently not be used like that (it works for me locally though), but I'm sure Yuxiao can save me!

Check for __customStack on haxe.Exception

---

src/jit.c

`fun_field_name` returns `const uchar *` (`const char16_t`) not `vbyte *` (`unsigned char *`)
GCC 14 has made the `incompatible-pointer-types` warning a hard error.

Fix compile error

---

other/haxelib/Run.hx

Related
- https://github.com/HaxeFoundation/hashlink/pull/706
@tobil4sk suggests that it's better to avoid the use of `make` on Windows, which isn't always available on a lot of systems (unless msys2 or cygwin is installed).

[hlc] Autocompilation on windows avoid use make

---

libs/ssl/CMakeLists.txt

The archive was replaced to fix a timestamp issue. See: https://github.com/Mbed-TLS/mbedtls/issues/10332
This fixes the failing android build

[cmake] Update hash for mbedtls 3.6.4

---

libs/openal/CMakeLists.txt

openal-soft has an LGPL license, which comes with some additional restrictions which are easier to fulfil when linking dynamically.
https://www.gnu.org/licenses/gpl-faq.en.html#LGPLStaticVsDynamic
It is still useful to have the OPENAL_STATIC flag, in case someone wants to link statically and is able to comply with the restrictions.

[cmake] Link with shared openal again on android

---

libs/ssl/CMakeLists.txt

Reverts HaxeFoundation/hashlink#802
See https://github.com/Mbed-TLS/mbedtls/issues/10332#issuecomment-3144297498

Revert "[cmake] Update hash for mbedtls 3.6.4"

---

other/haxelib/templates/make/Makefile

If we are not include uv.hdll in the program, then we don't need to link with -luv.
The reason we need to link -luv explicitly at all is due to #808.

[haxelib] Add -luv in Makefile only for uv.hdll

---

libs/directx/dx12.cpp

Fixes warnings:
```
...\hashlink\libs\directx\dx12.cpp(39,2): warning C4838: conversion from 'unsigned int' to 'int' requires a narrowing conversion
...\hashlink\libs\directx\dx12.cpp(40,2): warning C4838: conversion from 'unsigned int' to 'int' requires a narrowing conversion
```
These come up as errors on stricter compilers like mingw (though, dx12.hdll doesn't link on mingw still).

[dx12] Fix warning about unsigned int conversion
