CMakeLists.txt, appveyor.yml
Fix AppVeyor build and added missing vorbis lib in CMakeLists.txt
=> Fix AppVeyor build and added missing vorbis lib in CMakeLists.txt

Makefile, libs/ui/ui_stub.c
- Added compilation of UI, UV and OpenAL libs in Makefile
- Added stub functions for UI lib until we have a complete implementation
=> Mac: UI lib placeholder

libs/directx/dx/GameController.hx, libs/directx/gamecontroller.c
- Fixed mapping of some DirectInput controllers
- dx.GameController is now compatible with usesys
=> (DirectX) Improved GameController support

libs/directx/gamecontroller.c
Call `IDirectInput8_EnumDevices` only when we receive a `WM_DEVICECHANGE`.
In previous implementation EnumDevices was called every 500ms, which could cause perturbation on all USB devices connected.
=> Improved DirectInput device detection

libs/directx/directx.cpp, src/hl.h
While trying to compile hlc with directx I was having a bunch of linkage errors `unresolved external symbol `, adding `extern "C"` in front of the function in directx.cpp did the trick.
There might be a better way, if so I'd love to know it!
=> Adding `extern "C"` to HL_PRIM if using CPP

README.md
Add a note about building on ubuntu 16.04 linking to #147
=> Suggested note for ubuntu 16.04

src/jit.c
crash i ran into when updating clunky ball for latest hashlink and haxe 4 rc3.
same implementation as HF64 conversion but using `CVTSS2SI` instead of `CVTSD2SI`. dunno if this is the right way to do it, i haven't touched the jit before!
=> implement OToInt for HF32. fixes a crash

libs/sqlite/sqlite.c
=> Avoid double finalization by GC

src/std/sys.c
=> update hl_sys_time on Windows

src/std/maps.c, src/std/maps.h
See https://github.com/HaxeFoundation/haxe/pull/8681
=> Map.clear implementation

src/std/thread.c
porting nekovm code by @ncannasse  [suggestion](https://github.com/HaxeFoundation/haxe/issues/8699#issuecomment-525023553) at HaxeFoundation/haxe/issues/8699
=> add Lock bindings to thread.c

libs/sqlite/sqlite.c
=> fix sqlite cached string issue

libs/sdl/sdl.c
fixes https://github.com/HeapsIO/heaps/issues/717
=> Window size is properly restored after exiting fullscreen mode

libs/sqlite/sqlite.c
Fix errors related to GC calling result finalizer in case query tail (multiple queries and so on) and sql errors
=> fix sqlite result finalizer

src/std/thread.c
=> Lock blocking section

Makefile
I added some more configuration options to the main Makefile, mainly to support homebrew on MacOs.
=> provide fine-grained configuration options for bin/include/lib

src/hl.h, src/module.c
=> allow to pass struct* directly to C without wrapping

.github/dependabot.yml, .github/workflows/build.yml, README.md
This workflow runs on each commit/PR to verify it. When a commit is made to the main branch a GitHub pre-release named "latest" is created/updated containing binaries for linux/mac/win based on the last commit.
This also addresses #73
You can find an example here: https://github.com/sebthom/hashlink/releases/tag/latest
=> Add GitHub Actions workflow

.github/workflows/build.yml
Update github actions build config so it builds again after the latest changes to the VS project.
@ncannasse here you can see that the build works again https://github.com/sebthom/hashlink/runs/4418493367
=> Update github actions build config

src/debugger.c, src/hl.h, src/std/thread.c
=> Fix semaphores on MacOS.

.github/workflows/build.yml, src/std/debug.c
Puts in place change described here:
https://github.com/HaxeFoundation/hashlink/pull/529#issuecomment-1073691805
=> Fix linux 32 bit build

.github/workflows/build.yml
Forgot to uncomment this line 👀
=> Publish linux 32 bit build

.github/workflows/build.yml
Missed out a slash this time...
=> Publish linux 32 bit build (again)

libs/sqlite/sqlite.c, libs/sqlite/test/bin/.gitignore, libs/sqlite/test/src/BasicTestCase.hx, libs/sqlite/test/src/ExceptionTestCase.hx, libs/sqlite/test/src/Main.hx, libs/sqlite/test/src/ResultSetTestCase.hx, libs/sqlite/test/test.hxml
=> Fix invalid signature in sqlite.hdll (#485)

src/std/file.c
Added missing errno.h for Mac & linux.
=> Added missing header for errno.

libs/sdl/gl.c
As requested by @ncannasse: https://github.com/HaxeFoundation/hashlink/pull/644#issuecomment-1895316004
=> Throw instead of doing nothing in unsupported GL functions.

.github/workflows/build.yml, Makefile
=> [mac] Fix resolution of libhl.dylib when globally installed.

.github/workflows/build.yml
Fixes the warnings about node.js 16 actions being deprecated.
Closes #640
Closes #641
=> Update actions used in CI workflow.

src/jit.c
Fix https://github.com/HaxeFoundation/haxe/issues/11647
=> Fix OFloat not working for HF32

src/profile.c
=> Fix compilation with GCC 14.

other/haxelib/hlmem/Memory.hx
=> hlmem: Switch opt-in --color to opt-out --no-color

src/jit.c
=> Show better error for OGetMem using i64 on 32 bit

src/jit.c
Related Issue: https://github.com/HaxeFoundation/hashlink/issues/730
I don't really understand why `load(ctx, out, a)` doesn't work well when I added it before the "normal" case, but works in the current version. Otherwise haxe unit tests (and some added in my haxe PR) seems working now.
Some review would be helpful @ncannasse
=> [jit] Fix OSMOD/OSDIV overflow with INT_MIN / -1

src/jit.c
For https://github.com/HaxeFoundation/haxe/issues/11990
=> [Jit] Fix F32 NaN detection with x != x

src/hlc.h
Previous related implem
- https://github.com/HaxeFoundation/haxe/pull/11300
- https://github.com/HaxeFoundation/hashlink/commit/8d5c20810e4f1a89efc7218c5d69004e56b88075
Inspired by gc.c
https://github.com/HaxeFoundation/hashlink/blob/0c5d35fdbaad0e2cc4e24783367be51de50a3e46/src/gc.c#L30-L36
=> [hlc] fix prefetch not compiling

src/hlc.h, src/hlc_main.c
Highly inspired by the issue and hxcpp's solution x)
Closes https://github.com/HaxeFoundation/haxe/issues/11419
=> [hlc] add more undef

other/haxelib/templates/vs2019/Makefile, other/haxelib/templates/vs2022/Makefile, other/haxelib/templates/vs2022/__file__.sln, other/haxelib/templates/vs2022/__file__.vcxproj, other/haxelib/templates/vs2022/__file__.vcxproj.filters, other/haxelib/templates/vs2022/stdafx.c, other/haxelib/templates/vs2022/stdafx.h
It's 2025 now and maybe it's time to support vs2022 XD.
=> [templates] add vs2022 template and msbuild makefile

src/allocator.c, src/gc.c
Maybe for https://github.com/HaxeFoundation/hashlink/issues/747
When block is not actually a pointer.
Ping @ncannasse just in case
=> [gc] add some check for gc_flush_mark

src/hl.h
Unify Linux/macOS implementations and enable hl_debug_break for all non-console platforms.
Remove usage of .pushsection embed-breakpoint because it doesn't actually do anything.
Closes #764
=> Implement hl_debug_break for more architectures.

src/jit.c
Previously we detect null field access based on `OField` after `ONullCheck`. For example in `trace(a.foo)`
```
ONullCheck robj
OField _, robj[fid]
```
and we throw "Null access .foo" if a is null.
This PR extends it by
- Skip some const and operation such as int and addition before the actual detection: for `arr[i+2]`
- Detect `OSetField`: for `a.foo = i`
- Detect `OCall1/OCall2/...OCallN`: for `a.bar()`
=> [jit] Add more null access .f in ONullCheck

src/gc.c, src/hl.h, src/std/socket.c, src/std/sys.c
Just gets the basics of Hashlink to compile and run on Emscripten platform.
=> Add initial Emscripten compilation support.

other/haxelib/hlprof/ProfileGen.hx
Fake performance.measure events in the Chrome DevTools Performance timeline on hl.Profile.event (code > 0 with String).
- Start at event and end at next event or end-of-frame (code 0).
- Label with event code + event string.
=> [Profile] add custom event as performance.measure string in the timeline

src/std/sys.c
For https://github.com/Aidan63/haxe/issues/120
=> add millisecond resolution timer

src/hl.h, src/hlc_main.c, src/main.c, src/std/error.c, src/std/thread.c
https://github.com/HaxeFoundation/hashlink/pull/782 missed `hl_run_thread`.
=> Make uncaught exception printing consistent
